Algoritmo "Mensagem"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/07/2022
Var
// Seção de Declarações das variáveis 


Inicio
      // Seção de Comandos, procedimento, funções, operadores, etc...

     Escreva ("Pai e Mãe, espero que sejam felizes e tenham muita saúde.")

Fimalgoritmo